CREATE DATABASE BANCO_DA_WEMI;

USE BANCO_DA_WEMI;

CREATE TABLE CONTA_CORRENTE(
NUMERO integer NOT NULL PRIMARY KEY,
SALDO decimal (10,2) NOT NULL,
NOME varchar (100) NOT NULL);

INSERT INTO CONTA_CORRENTE VALUES
(1001, 900.68, "Leticia Barros"),
(1002, 100.50, "Júlia Cardoso Miranda"),
(1003, 10000.00, "Felipe Becari"),
(1004, 370.75, "Wendy Laysla"),
(1005, 437.90, "Thais Sitibaldi"),
(1006, 593.60, "Victor Leal"),
(1007, 1178.45, "Tabata Silva"),
(1008, 7000.00, "Wemilli Lima"),
(1009, 224.15, "Isabella Nunes"),
(1010, 5327.98, "Guilherme Alves"),
(1011, 426.86, "Hiago Teodoro"),
(1012, 543.45, "Ana Júlia Marques"),
(1013, 542.19, "Tereza Lima"),
(1014, 65257.00, "Thaissa Candela"),
(1015, 6590.00, "Rafaela Balerini");

SELECT * FROM CONTA_CORRENTE;

DELIMITER //
CREATE PROCEDURE TRANFERENCIA(
IN ORIGEM integer,
IN DESTINO integer,
IN VALOR DECIMAL (10,2)
)
BEGIN
DECLARE SALDO_ORIGEM DECIMAL(10,2);
DECLARE SALDO_DESTINO DECIMAL(10,2);

SELECT SALDO INTO SALDO_ORIGEM FROM CONTA_CORRENTE WHERE NUMERO = ORIGEM;
SELECT SALDO INTO SALDO_DESTINO FROM CONTA_CORRENTE WHERE NUMERO =
DESTINO;

IF SALDO_ORIGEM < VALOR THEN
	SELECT "SALDO INSUFICIENTE PARA TRANSFERENCIA";

ELSE
	SELECT "TRANSFERENCIA AUTORIZADA";

UPDATE CONTA_CORRENTE SET SALDO = (SALDO_ORIGEM - VALOR) WHERE NUMERO =
ORIGEM;
SELECT "VALOR R$",VALOR," SACADO DA CONTA ",ORIGEM;
UPDATE CONTA_CORRENTE SET SALDO = (SALDO_DESTINO + VALOR) WHERE NUMERO =
DESTINO;

SELECT "VALOR R$",VALOR," DEPOSITADO NA CONTA",DESTINO;

END IF;
END//
DELIMITER ;

CALL TRANFERENCIA (1002, 1001, 50);

CREATE TABLE MOVIMENTACAO(
NUMERO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
CONTA INTEGER NOT NULL,
SALDO_ANTERIOR DECIMAL(10,2) NOT NULL,
SALDO_ATUAL DECIMAL(10,2) NOT NULL
);

DELIMITER //
CREATE TRIGGER ATUALIZA_MOVIMENTACAO
AFTER UPDATE ON CONTA_CORRENTE
FOR EACH ROW
BEGIN
INSERT INTO MOVIMENTACAO

(CONTA, SALDO_ANTERIOR, SALDO_ATUAL)
VALUES
(OLD.NUMERO, OLD.SALDO, NEW.SALDO);

END
//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SACAR(
IN ORIGEM integer,
IN VALOR DECIMAL (10,2)
)
BEGIN
DECLARE SALDO_ORIGEM DECIMAL(10,2);

SELECT SALDO INTO SALDO_ORIGEM FROM CONTA_CORRENTE WHERE NUMERO = ORIGEM;

IF SALDO_ORIGEM < VALOR THEN
	SELECT "SALDO INSUFICIENTE PARA O SAQUE";

ELSE
	SELECT "SAQUE AUTORIZADO";

UPDATE CONTA_CORRENTE SET SALDO = (SALDO_ORIGEM - VALOR) WHERE NUMERO =
SALDO_ORIGEM;
SELECT "VALOR R$",VALOR,"SACADO DA CONTA", ORIGEM;
END IF;

END//
DELIMITER ;

CALL SACAR (1002, 50.07);

DELIMITER //
CREATE PROCEDURE DEPOSITAR(
IN DESTINO integer,
IN VALOR DECIMAL (10,2)
)
BEGIN
DECLARE SALDO_DESTINO DECIMAL(10,2);

SELECT SALDO INTO SALDO_DESTINO FROM CONTA_CORRENTE WHERE NUMERO =
DESTINO;

IF VALOR < VALOR THEN

SELECT "NÃO FOI POSSIVEL EFETUAR O DEPOSITO";

ELSE

SELECT "DEPOSITO EFETUADO";

UPDATE CONTA_CORRENTE SET SALDO = (SALDO_DESTINO + VALOR) WHERE NUMERO =
DESTINO;
SELECT "VALOR R$",VALOR," DEPOSITADO NA CONTA", DESTINO;
END IF;

END//
DELIMITER ;

CALL DEPOSITAR (1002, 200);

SET SQL_SAFE_UPDATES=0;

DELIMITER //
CREATE PROCEDURE SETAR_SALDO(
in DESTINO INTEGER,
IN VALOR DECIMAL(10,2)
)
BEGIN

SELECT SALDO FROM CONTA_CORRENTE WHERE NUMERO = DESTINO;

IF DESTINO>=1000 AND DESTINO<=1004 THEN
SELECT "SETANDO DADOS";

UPDATE CONTA_CORRENTE SET SALDO = VALOR WHERE NUMERO = DESTINO;
SELECT "VALOR SETADO", VALOR, " NA CONTA ", DESTINO;
ELSE
SELECT "VALORES INVÁLIDOS";
END IF;

END//
DELIMITER ;

CALL SETAR_SALDO (1003,10500);

DELIMITER //
CREATE PROCEDURE SALDO_MAIOR(
in VALOR DECIMAL(10,2)
)
BEGIN
SELECT * FROM conta_corrente WHERE SALDO>VALOR ORDER BY SALDO DESC;
END //
DELIMITER ;

CALL SALDO_MAIOR (200);

DELIMITER //
CREATE PROCEDURE SALDO_MENOR(
in VALOR DECIMAL(10,2)
)
BEGIN
SELECT * FROM conta_corrente WHERE SALDO<VALOR ORDER BY SALDO DESC;
END //
DELIMITER ;

CALL SALDO_MENOR (500);

select * from MOVIMENTACAO;